switches:
    -   name: FabricA
        host: 172.23.60.238
        username: admin
        password: CDSi2012
        vsan: 1
        zoneset: SW238VSAN1

    -   name: FabricB
        host: 172.23.60.238
        username: admin
        password: CDSi2012
        vsan: 2
        zoneset: SW238VSAN2


apphost:
    host: 172.23.60.121
    username: root
    password: CDSi101

#    host entity ID in source storage
    host_entity_id_in_storage : 2

    ports:
        -   name: AppHostC1_i1
            wwpn: 21000024ff69dca1
            switch: FabricA
            switch_interface: fc1/4
        -   name: AppHostC1_i2
            wwpn: 21000024ff69dcab
            switch: FabricA
            switch_interface: fc1/37

storage:
    source:
        vendor: CirrusData
        host: 172.23.60.197
        username: admin
        password: CDSi101
        targets:
            -   name: SRC_T1
                wwpn: 21000060166cc13c
            -   name: SRC_T2
                wwpn: 21000060166cc13d
    destination:
        vendor: Pure
        host: 192.168.2.8
        fa_api_token: 852ebbc2-2ac7-db06-8834-761abc477792
        targets:
            -   name: PURE_T1
                wwpn: 524a93781d6ca500
            -   name: PURE_T2
                wwpn: 524a93781d6ca510

dms:
    host: 172.23.60.125
    username: admin
    password: CDSi101

    nexus:
        -   name: DMS-125-Nexus1
            switch: FabricA
            upstream_switch_interface: fc1/3
            downstream_switch_interface: fc1/4

        -   name: DMS-126-Nexus1
            switch: FabricB
            upstream_switch_interface: fc1/35
            downstream_switch_interface: fc1/36

    initiators:
        -   name: DMS-125-120
            port: 120
            wwpn:  21000024ff69dca8
            switch: FabricA
            switch_interface: fc1/5

        -   name: DMS-126-120
            port: 120
            wwpn: 21000024ff698184
            switch: FabricB
            switch_interface: fc1/37

insertion:
    -   nexus: DMS-125-Nexus1
        initiator: AppHostC1_i1
        target: SRC_T1
        virtual_initiator_wwpn: 21013a5e0369dca1
        virtual_target_wwpn: 21013a5e036cc13c

##################
# Destination Zoning
#
# This section should define which DMS initiators should be zoned with which targets from new storage
##################
destination_zoning:
    - target: PURE_T1
      dms_initiator: DMS-125-120
    - target: PURE_T2
      dms_initiator: DMS-126-120

migration:
    source_volumes:
        -   uuid: 60060163-00ad-a8e9-6656-000000000006
            name: DiskA
        -   uuid: 60060163-00ad-a8e9-6656-000000000007
            name: DiskB
        -   uuid: 60060163-00ad-a8e9-6656-000000000008
            name: DiskC
        -   uuid: 60060163-00ad-a8e9-6656-000000000009
            name: DiskK

##################
# Post Cut-over Zoning
#
# Zones will be created during cut-over process.
# This section should define which host initiators should be zoned with which targets from new storage
##################
post_cutover_zoning:
    - target: PURE_T1
      initiator: AppHostC1_i1
    - target: PURE_T2
      initiator: AppHostC1_i2