ungrouped:
    hosts:
        initiator:
        source_storage:
        destination_storage:
        switch:
            ansible_connection: ansible.netcommon.network_cli
            ansible_network_os: cisco.nxos.nxos

